export enum EUserAction {
  USER_GET_INFO_BY = 'USER:GET_INFO',
  USER_CHANGE_PASSWORD = 'USER:CHANGE_PASSWORD',
  USER_CHANGE_PROFILE = 'USER:CHANGE_PROFILE',
  USER_CHANGE_AVATAR = 'USER:CHANGE_AVATAR',
  ERROR_USER_GET_INFO_BY = 'USER:ERROR:GET_INFO',
  ERROR_USER_CHANGE_PASSWORD = 'USER:ERROR:CHANGE_PASSWORD',
  ERROR_USER_CHANGE_PROFILE = 'USER:ERROR:CHANGE_PROFILE',
  ERROR_USER_CHANGE_AVATAR = 'USER:ERROR:CHANGE_AVATAR',
  USER_UNKNOWN = 'USER:UNKNOWN',
}
