version: '3.7'

services:
  arcnd:
    build:
      context: .
    ports:
      - "3000:5000"
    depends_on:
      - postgres
    networks:
      - arcnd-network
    restart: always
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - '6432:5432'
    volumes:
      - vol-pg:/var/lib/postgresql/data
    environment:
      PG_USER: ${PG_USER}
      PG_DB: ${PG_DB}
      PG_PASS: ${PG_PASS}
      PGDATA: /var/lib/postgresql/data
    networks:
      - arcnd-network
    restart: always

networks:
  arcnd-network:
    driver: bridge

volumes:
  vol-pg:
    driver: local
