export enum EGameAction {
  INC_SCORE = 'GAME:INC_SCORE',
  DEC_LIVE = 'GAME:DEC_LIVE',
  END_GAME = 'GAME:END_GAME',
  START_GAME = 'GAME:START_GAME',
  INC_LEVEL = 'GAME:INC_LEVEL',
  GO = 'GAME:GO',
}
