import { Messages, Topics } from 'Pages/Forums/types';

export const data: Topics = [
  {
    id: '1',
    description: 'First topic',
    messageCount: 20,
    author: 'Oleg',
    authorId: 1,
    lastMessage: 'Test last message',
    lastMessageTime: 9000000,
    createTime: 8000000,
    lastMessageUser: 'Nikolay Sidorov',
    lastMessageUserId: 2,
  },
  {
    id: '2',
    description: 'Second topic',
    messageCount: 20,
    author: 'Alexandr Stepanov',
    authorId: 3,
    lastMessage: 'Test last message on topic 2',
    lastMessageTime: 10000000,
    createTime: 8500000,
    lastMessageUser: 'Nikolay Sidorov',
    lastMessageUserId: 2,
  },
  {
    id: '3',
    description: '3 topic',
    messageCount: 2,
    author: 'Alexandr Stepanov',
    authorId: 3,
    lastMessage: 'Test last message on topic 2',
    lastMessageTime: 10000000,
    createTime: 8500000,
    lastMessageUser: 'Mrak',
    lastMessageUserId: 2,
  },
  {
    id: '4',
    description: '4 topic',
    messageCount: 10,
    author: 'Ostap Bender',
    authorId: 3,
    lastMessage: 'Test last message on topic 4',
    lastMessageTime: 10000000,
    createTime: 8500000,
    lastMessageUser: 'Mark',
    lastMessageUserId: 2,
  },
];

export const messages: Messages = [
  {
    id: '1',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '2',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '3',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '4',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '5',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '6',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '7',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '8',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '9',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '10',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '11',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '12',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '13',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '14',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '15',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '16',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '17',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '18',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '19',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '20',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '21',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
  {
    id: '22',
    topic: '1',
    message: 'Sample message for topic 1',
    author: 'Oleg',
    authorId: 1,
    header: 'header -> Whats up',
    parentMessage: 0,
    time: 9000000,
  },
];
