name: CD nairobi-arcnd-4.ya-praktikum.tech
on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

#env:
#  FIRST_NAME: Terry 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to YC
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /work/ARCND
            git checkout deploy
            git pull
            docker-compose build
            docker-compose up -d
          host: ${{ secrets.HOST }}
          username: deploy
          passphrase: ${{ secrets.PASS }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: Notify
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
